services:
  db:
    image: mariadb:10.11
    container_name: mmi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mmi_wp_db
      MYSQL_USER: mmi_user
      MYSQL_PASSWORD: mmi_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: .
    container_name: mmi_app
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: mmi_user
      WORDPRESS_DB_PASSWORD: mmi_password
      WORDPRESS_DB_NAME: mmi_wp_db
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data: